# dev开发环境
# mysql - local - url
spring:
  application:
    name: match-api
  datasource:
#          name: dev
#          url: jdbc:mysql://127.0.0.1:3306/cjmatch?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#          username: root
#          password: root
          url: jdbc:mysql://172.28.3.45:20010/cj_match?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: cj_weng
          password: 123456
#          url: jdbc:mysql://47.100.222.71:3306/cj_match?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#          username: m_match
#          password: YEMINHE2du0xYBna
#           使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
  cloud:
      consul:
        host: 172.28.3.45
        port: 8500
        discovery:
          register: false
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    expire-time: 120
#  rabbitmq:
#      host: 172.28.3.45
#      port: 5672
#      username: test
#      password: test
#      cache:
#        channel:
#          size: 100
#          checkout-timeout: 1000
#        connection:
#            size: 5
#      connection-timeout: 3000
#      virtual-host: /


# file-system config
seaweed:
  ip: 172.28.3.45
  port: 9333

# wechat config
wechat:
#  app-id: wxbea125c311c43dd2
  app-id: wx66eab4b767e88ff9
  redirect-uri: http://demo.com
#  app-secret: 78717f140c4394ce13a345a0242ae3c7
  app-secret: 81653ea574f7a2dbc3e6cffd5be1a345

# server config
server:
  port: 8888
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  tomcat:
    uri-encoding: UTF-8
# uc-api module config
#ucapi:
#    service-name: uc
#    app-id: platform_app
#    secret: 1ArLkQgVaWUYFPHv7NwzkpudzDFsfsaQ
#    pool-max-total: 50
#    pool-block-when-exhausted: true
#    pool-max-wait-millis: -1
#    pool-min-evictable-idle-time-millis: 600000
#    pool-max-idle: 10
#    pool-min-idle: 0



# cj-match config
cjmatch:
  vaild:
    template: 429246
    app-template: 425206
    limit: 5
    expires: 60

# keycloak config
#keycloak:
#  realm: match-platform
#  auth-server-url: http://localhost:8080/auth
#  public-client: true
#  ssl-required: none
#  resource: match-app
#  credentials:
#    secret: 5ab301b3-5d9e-4bd6-9231-ceae1df97ba7
#    use-resource-role-mappings: true
#  securityConstraints[0]:
#    authRoles[1]: user
#    securityCollections[0]:
#      name: user
#      patterns[0]: /v1/match
#  securityConstraints[1]:
#    authRoles[0]: admin
#    securityCollections[0]:
#      name: admin
#      patterns[0]: /v1/match/manage